sylius_resource:
    resources:
        bitbag_sylius_bonus_points.bonus_points:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusBonusPointsPlugin\Entity\BonusPoints
                interface: BitBag\SyliusBonusPointsPlugin\Entity\BonusPointsInterface
                repository: BitBag\SyliusBonusPointsPlugin\Repository\BonusPointsRepository
