sylius_resource:
    resources:
        bitbag_sylius_bonus_points.bonus_points_strategy:
            driver: doctrine/orm
            classes:
                model: BitBag\SyliusBonusPointsPlugin\Entity\BonusPointsStrategy
                interface: BitBag\SyliusBonusPointsPlugin\Entity\BonusPointsStrategyInterface
                form: BitBag\SyliusBonusPointsPlugin\Form\Type\BonusPointsStrategyType
